version: 2

workspace: &workspace
    ~/PoseEstimationForMobile

android_build_environment: &android_build_environment
    working_directory: *workspace
    docker:
        - image: circleci/android:api-28-ndk-r17b
    environment:
        JVM_OPTS: -Xmx3200m

cache_key: &cache_key
    key: jars-{{ checksum "android_demo/demo_tflite/build.gradle" }}-{{ checksum "android_demo/demo_tflite/app/build.gradle" }}-{{ checksum "android_demo/demo_tflite/gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "android_demo/demo_mace/build.gradle" }}-{{ checksum "android_demo/demo_mace/app/build.gradle" }}-{{ checksum "android_demo/demo_mace/gradle/wrapper/gradle-wrapper.properties" }}

restore_cache: &restore_cache
    restore_cache:
        <<: *cache_key

save_cache: &save_cache
    save_cache:
        <<: *cache_key
        paths:
            - android_demo/demo_tflite/.gradle/caches
            - android_demo/demo_tflite/.gradle/wrapper
            - android_demo/demo_mace/.gradle/caches
            - android_demo/demo_mace/.gradle/wrapper
            - ~/.m2

persist_tflite_apk_to_workspace: &persist_tflite_apk_to_workspace
    persist_to_workspace:
        root: .
        paths:
            - android_demo/demo_tflite/app/build/outputs/apk

persist_apk_to_workspace: &persist_apk_to_workspace
    persist_to_workspace:
        root: .
        paths:
            - android_demo/demo_tflite/app/build/outputs/apk
            - android_demo/demo_mace/app/build/outputs/apk

attach_workspace: &attach_workspace
    attach_workspace:
        at: *workspace

jobs:
    build:
        <<: *android_build_environment
        steps:
            - checkout 
            - *restore_cache

            - run:
                name: Generating tflite apk
                command: |
                    cd android_demo/demo_tflite
                    ./gradlew :app:assembleDebug
            - store_artifacts:
                path: android_demo/demo_tflite/app/build/outputs/apk
                destination: apk

            - setup_remote_docker:  
                docker_layer_caching: true
            - run:
                name: Generating mace apk
                command: |
                    docker pull registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
                    docker run -it --privileged -d --name mace-dev --net=host -v /home/circleci/PoseEstimationForMobile/android_demo/demo_mace:/demo_mace registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
                    docker exec -it mace-dev bash
                    cd /demo_mace
                    rm -rf local.properties
                    ./gradlew :app:assembleDebug
                no_output_timeout: 30m
            - store_artifacts:
                path: android_demo/demo_mace/app/build/outputs/apk
                destination: apk

            - *save_cache
            - *persist_apk_to_workspace

    # upload_apk:
    #     <<: *android_build_environment
    #     steps:
            
